{% set name = "Flask" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 315ded2ddf8a6281567edb27393010fe3406188bafbfe65a3339d5787d89e477

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - flask = flask.cli:main
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools

  run:
    - python >=3.7
    - click >=8.0
    # should be py<310 but we want to keep this noarch: python
    - importlib-metadata  >=3.6.0
    - itsdangerous >=2.0
    - jinja2 >=3.0
    - werkzeug >=2.0

test:
  requires:
    - pip
  imports:
    - flask
    - flask.json
  commands:
    - flask --help
    - pip check

about:
  home: http://flask.pocoo.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A microframework based on Werkzeug, Jinja2 and good intentions.
  description: |
    Flask is a microframework for Python based on Werkzeug and Jinja2. It's
    intended for getting started very quickly and was developed with best
    intentions in mind.
  doc_url: http://flask.pocoo.org/docs/1.0/
  doc_source_url: https://github.com/pallets/flask/blob/master/docs/index.rst
  dev_url: https://github.com/pallets/flask

extra:
  recipe-maintainers:
    - goanpeca
    - nehaljwani
    - ukaratay
    - marcelotrevisani
    - xylar
